# use light version of NodeJS
FROM node:lts-alpine

# set the working directory
WORKDIR /usr/src/app

# copy package.json & 'package-lock.json' into the container
COPY package*.json ./

# install dependencies
RUN npm install

# Copy files into the container
COPY . ./

# expose port 3000
EXPOSE 3000

# run the app
CMD ["npm", "run", "start:watch"]